### ISSUE TITLE
Test case tolerances too tight

### ISSUE THREAD

**Issue by ConnorStoneAstro** [Ciela-Institute/caustic#18]
Test cases have tolerances set at very specific values. Should be reset to generic values which will not trip over small numerical fluctuations.

**Comment by adam-coogan** [comment]
Fixed in 71a10a47f2ef0c94a1acdadd047470ae0ed82f69 and e7af7119056c8a70ceaacd24b4d851a82f076ce5. Getting the Windows + python 3.10 required bumping the dependency versions in `requirements.txt`, for some reason...
