### ISSUE TITLE
Integrate lensing Jacobian FFT calculation

### ISSUE THREAD

**Issue by adam-coogan** [Ciela-Institute/caustic#26]
This issue is centered around `_lensing_jacobian_fft_method`. There are a few tasks:
- Refactor into `lenses.utils` so the function can be used in `ThickLens` and `ThinLens`
- Implement toggle between this method and the `jacfwd` + `vmap` one (similar to `KappaGrid`)
- Add tests

**Comment by ConnorStoneAstro** [comment]
Closed by #65
