### ISSUE TITLE
Batching throughout caustic

### ISSUE THREAD

**Issue by ConnorStoneAstro** [Ciela-Institute/caustic#34]
Need to solve batching for all of caustic. Under consideration we could use vmap, enforce batching always, or try to make everything shape agnostic. Its very hard to be shape agnostic for some functions though.

**Comment by AlexandreAdam** [comment]
Current main branch supports `vmap`, which is tested on two simulator covering some parametric and some pixelated modules. Should we add more test, otherwise I think this issue should be closed.
