### ISSUE TITLE
Implement "to" method for all objects

### ISSUE THREAD

**Issue by ConnorStoneAstro** [Ciela-Institute/caustic#48]
A recursively applied to method should put every pytorch object onto the correct dtype and device. Should maybe also be a method for "packed"

**Comment by AlexandreAdam** [comment]
Looking inside the `Parametrized` module, it seems the `to` method is already recursive. We should probably just add test to make sure the `to` method behaves as we expect. 

The [Parametrized update](https://github.com/Ciela-Institute/caustic/pull/50) already has some changes to the module and added test. We could add those there.
