### ISSUE TITLE
Scale parameter of pixelated simulator

### ISSUE THREAD

**Issue by mjyb16** [Ciela-Institute/caustic#61]
Need to make sure the "scale" parameter is the pixel scale of the source image in arcseconds. It should not be the source field of view.

**Comment by AlexandreAdam** [comment]
This is fixed in this [commit](https://github.com/Ciela-Institute/caustic/commit/83fc50a67082f7219b8a30ee5fc8ebf0c94d449c).

**Comment by mjyb16** [comment]
Indeed it is!
